spring.application.neme=ajax_app_java
spring.sql.int.move=always
spring.datasource.driverClassName=org.postgresql.Driver
sprong.datasource.url=${DATABASE_URL}
mybatis.configuration.map-under-to-comel-case=true